### ISSUE TITLE
Issue with %realpermissions_rank_prefix% Placeholder Causing NullPointerException

### ISSUE THREAD

**Issue by relizth** [joserodpt/RealPermissions#2]
When using the `%realpermissions_rank_prefix%` placeholder in conjunction with the TAB plugin, the system throws a `NullPointerException`. This error appears to be due to the player object being `null` at the time of accessing the `getRank()` function. Below is the error log:

**Steps to Reproduce:**
1. Set up the RealPermissions and TAB plugins.
2. Use the `%realpermissions_rank_prefix%` placeholder in TAB.
3. Notice the `NullPointerException` error in the logs when a player joins or placeholder is requested.

**Expected Behavior:**
The `%realpermissions_rank_prefix%` should return the player’s rank prefix without error.

**Additional Context:**
TAB version: 5.0.2-SNAPSHOT  
RealPermissions version: 0.4.2
Server version: 1.21.1-128-master@d348cb8

Any assistance or suggestions for configuring the placeholder correctly would be greatly appreciated.

Thank you!

```
29.10.2024 - 20:04:56 - [TAB v5.0.2-SNAPSHOT] Player placeholder %realpermissions_rank_prefix% generated an error when setting for player ZacharyDelightz
29.10.2024 - 20:04:56 - java.lang.NullPointerException: Cannot invoke "joserodpt.realpermissions.api.player.RPPlayer.getRank()" because "p" is null
29.10.2024 - 20:04:56 - 	at joserodpt.realpermissions.plugin.RealPermissionsPlaceholderAPI.onRequest(RealPermissionsPlaceholderAPI.java:108)
29.10.2024 - 20:04:56 - 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
29.10.2024 - 20:04:56 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
29.10.2024 - 20:04:56 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:185)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:153)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.getLastValue(PlayerPlaceholderImpl.java:131)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.placeholders.types.TabPlaceholder.set(TabPlaceholder.java:83)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.Property.update(Property.java:271)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.Property.analyze(Property.java:164)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.Property.<init>(Property.java:109)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.platform.TabPlayer.loadPropertyFromConfig(TabPlayer.java:270)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.features.PlayerList.loadProperties(PlayerList.java:95)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.features.PlayerList.onJoin(PlayerList.java:267)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.FeatureManager.lambda$onJoin$4(FeatureManager.java:186)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:192)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:28)
29.10.2024 - 20:04:56 - 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
29.10.2024 - 20:04:56 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
29.10.2024 - 20:04:56 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
29.10.2024 - 20:04:56 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
29.10.2024 - 20:04:56 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
29.10.2024 - 20:04:56 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
29.10.2024 - 20:04:56 - 	at java.base/java.lang.Thread.run(Thread.java:1583)
29.10.2024 - 20:07:55 - [TAB v5.0.2-SNAPSHOT] Player placeholder %realpermissions_rank_prefix% generated an error when setting for player ZacharyDelightz
29.10.2024 - 20:07:55 - java.lang.NullPointerException: Cannot invoke "joserodpt.realpermissions.api.player.RPPlayer.getRank()" because "p" is null
29.10.2024 - 20:07:55 - 	at joserodpt.realpermissions.plugin.RealPermissionsPlaceholderAPI.onRequest(RealPermissionsPlaceholderAPI.java:108)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:185)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:153)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.getLastValue(PlayerPlaceholderImpl.java:131)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.placeholders.types.TabPlaceholder.set(TabPlaceholder.java:83)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.Property.update(Property.java:271)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.Property.analyze(Property.java:164)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.Property.<init>(Property.java:109)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.platform.TabPlayer.loadPropertyFromConfig(TabPlayer.java:270)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.features.PlayerList.loadProperties(PlayerList.java:95)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.features.PlayerList.onJoin(PlayerList.java:267)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.FeatureManager.lambda$onJoin$4(FeatureManager.java:186)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:192)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:28)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
29.10.2024 - 20:07:55 - 	at java.base/java.lang.Thread.run(Thread.java:1583)
29.10.2024 - 20:07:55 - [TAB v5.0.2-SNAPSHOT] Player placeholder %realpermissions_rank_prefix% generated an error when setting for player ZacharyDelightz
29.10.2024 - 20:07:55 - java.lang.NullPointerException: Cannot invoke "joserodpt.realpermissions.api.player.RPPlayer.getRank()" because "p" is null
29.10.2024 - 20:07:55 - 	at joserodpt.realpermissions.plugin.RealPermissionsPlaceholderAPI.onRequest(RealPermissionsPlaceholderAPI.java:108)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
29.10.2024 - 20:07:55 - 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:185)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:153)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.placeholders.PlaceholderRefreshTask.run(PlaceholderRefreshTask.java:59)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.lambda$refresh$1(PlaceholderManagerImpl.java:82)
29.10.2024 - 20:07:55 - 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
29.10.2024 - 20:07:55 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
29.10.2024 - 20:07:55 - 	at java.base/java.lang.Thread.run(Thread.java:1583)
29.10.2024 - 20:10:20 - [TAB v5.0.2-SNAPSHOT] Player placeholder %realpermissions_rank_prefix% generated an error when setting for player ZacharyDelightz
29.10.2024 - 20:10:20 - java.lang.NullPointerException: null
```

**Comment by joserodpt** [comment]
Hi! Just saw your issue, sorry for the delay.
Please test the provided jar file:
[RealPermissions.jar.zip](https://github.com/user-attachments/files/18240868/RealPermissions.jar.zip)
Thanks and happy Christmas! :)
